### ISSUE TITLE
.NET Framework compatibility issue

### ISSUE THREAD

**Issue by atroul** [mskcc/Medidata.RWS.NET#13]
I tried to install Medidata.RWS.NET via nuget but I get this error message:

> Install-Package : Could not install package 'Medidata.RWS.NET 1.0.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly 
references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by mattkoch614** [comment]
The package targets .NET 4.5.2. You'll need to install into a project that targets that version of .NET or higher.

**Comment by nikolayrusev** [comment]
Dear Matt,

What is the framework used for Medidata.RWS.NET.Standard 1.0.2?

Thank you!
Nik

**Comment by mattkoch614** [comment]
The “standard” version of this library was built using .Net Standard 2.0.

**Comment by nikolayrusev** [comment]
I tried to install the Standard package published on 16.8.2018.
Even when using 4.5.2: I receive this error msg:

"Installing 'Medidata.RWS.NET.Standard 1.0.2'.
Successfully installed 'Medidata.RWS.NET.Standard 1.0.2'.
Adding 'Medidata.RWS.NET.Standard 1.0.2' to 02. File-Copy.
Uninstalling 'Medidata.RWS.NET.Standard 1.0.2'.
Successfully uninstalled 'Medidata.RWS.NET.Standard 1.0.2'.
Install failed. Rolling back...
Could not install package 'Medidata.RWS.NET.Standard 1.0.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by nikolayrusev** [comment]
> The “standard” version of this library was built using .Net Standard 2.0.

4.6.1 - Thanks!
